apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linking-data-pvc
  namespace: linkding
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
