apiVersion: v1
kind: Service
metadata:
  name: linkding-svc
  namespace: linkding
spec:
  selector:
    app: linkding
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: LoadBalancer

