apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-np
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-np
  template:
    metadata:
      labels:
        app: nginx-np
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-np
spec:
  type: NodePort
  selector:
    app: nginx-np
  ports:
    - port: 9090
      targetPort: 80
      nodePort: 30007 # range(30000 - 32767)
