apiVersion: v1
kind: Service
metadata: 
  namespace: mealie
  name: mealie-lb-svc
spec:
  type: LoadBalancer
  selector:
    app: mealie
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9000
