apiVersion: v1
kind: Service
metadata: 
  name: nginx-lb-svc
  namespace: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx-lb
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
